In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("messy_customer_data.csv")

In [3]:
df.head()

,CustomerID,Name,Gender,Age,City,Signup_Date,Last_purchase_date,purchase_amount,feedback_score,email,Phone_number,Country
0,NaN,Ankit,F,36.0,Mumbai,31/12/2024,13/08/2025,-999.0,2.0,NaN,0,Canada
1,C2,Ravi,Female,NaN,Kolkata,NaN,NaN,NaN,-1.0,user1mail.com,abc123,Canada
2,3,Ravi,female,66.0,Ahmedabad,NaN,20/06/2023,NaN,10.0,user2@mail.com,abc123,India
3,C4,Ankit,male,44.0,Kolkata,NaN,13/09/2025,NaN,NaN,NaN,9316267914,USA
4,5,Rahul,Male,200.0,Ahmedabad,09/07/2025,NaN,-999.0,NaN,user4mail.com,9234603292,USA

In [4]:
df.shape

(10000, 12)

# Data Cleaning

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.isna().sum()

CustomerID            2379
Name                  1658
Gender                2455
Age                   2576
City                  1130
Signup_Date           2529
Last_purchase_date    3286
purchase_amount       5033
feedback_score        2462
email                 5066
Phone_number          2444
Country               1704
dtype: int64

In [7]:
df.isna().mean() * 100

CustomerID            23.79
Name                  16.58
Gender                24.55
Age                   25.76
City                  11.30
Signup_Date           25.29
Last_purchase_date    32.86
purchase_amount       50.33
feedback_score        24.62
email                 50.66
Phone_number          24.44
Country               17.04
dtype: float64

In [8]:
df['CustomerID'] = df['CustomerID'].astype("string").str.strip().str.replace("C", "", regex=False)

df['CustomerID'] = pd.to_numeric(df['CustomerID'], errors="coerce")

df['CustomerID'] = df['CustomerID'].fillna(
    pd.Series(range(1, len(df) + 1), index=df.index)
)

df['CustomerID'] = ("C" + df['CustomerID'].astype(int).astype(str))

In [9]:
df.head()

,CustomerID,Name,Gender,Age,City,Signup_Date,Last_purchase_date,purchase_amount,feedback_score,email,Phone_number,Country
0,C1,Ankit,F,36.0,Mumbai,31/12/2024,13/08/2025,-999.0,2.0,NaN,0,Canada
1,C2,Ravi,Female,NaN,Kolkata,NaN,NaN,NaN,-1.0,user1mail.com,abc123,Canada
2,C3,Ravi,female,66.0,Ahmedabad,NaN,20/06/2023,NaN,10.0,user2@mail.com,abc123,India
3,C4,Ankit,male,44.0,Kolkata,NaN,13/09/2025,NaN,NaN,NaN,9316267914,USA
4,C5,Rahul,Male,200.0,Ahmedabad,09/07/2025,NaN,-999.0,NaN,user4mail.com,9234603292,USA

In [10]:
df['Gender'] = df['Gender'].astype("string").str.strip().str.lower()

df['Gender'] = df['Gender'].replace({
    "m": "Male",
    "male": "Male",
    "f": "Female",
    "female": "Female"
})

In [11]:
df.loc[(df['Age'] < 0) | (df['Age'] > 100), "Age"] = np.nan

df['Age'] = df['Age'].round().astype("Int64")

In [12]:
df['Signup_Date'] = pd.to_datetime(
    df['Signup_Date'],
    format="%d/%m/%Y",
    errors="coerce"
)

In [13]:
df['Last_purchase_date'] = pd.to_datetime(
    df['Last_purchase_date'],
    format="%d/%m/%Y",
    errors="coerce"
)

In [14]:
df.loc[df['purchase_amount'] < 0, "purchase_amount"] = np.nan

In [15]:
df.loc[~df['feedback_score'].between(0, 10), "feedback_score"] = np.nan

In [16]:
email_pattern = r"^[^@\s]+@[^@\s]+\.[^@\s]+$"

valid_email = df["email"].astype("string").str.match(
    email_pattern,
    na = False
)

df.loc[~valid_email, "email"] = np.nan

In [17]:
df["Phone_number"] = df["Phone_number"].astype("string").str.strip()

valid_phone = df["Phone_number"].str.fullmatch(
    r"\d{10}",
    na=False
)

df.loc[~valid_phone, "Phone_number"] = np.nan

In [18]:
df.head()

,CustomerID,Name,Gender,Age,City,Signup_Date,Last_purchase_date,purchase_amount,feedback_score,email,Phone_number,Country
0,C1,Ankit,Female,36,Mumbai,2024-12-31,2025-08-13,NaN,2.0,NaN,<NA>,Canada
1,C2,Ravi,Female,<NA>,Kolkata,NaT,NaT,NaN,NaN,NaN,<NA>,Canada
2,C3,Ravi,Female,66,Ahmedabad,NaT,2023-06-20,NaN,10.0,user2@mail.com,<NA>,India
3,C4,Ankit,Male,44,Kolkata,NaT,2025-09-13,NaN,NaN,NaN,9316267914,USA
4,C5,Rahul,Male,<NA>,Ahmedabad,2025-07-09,NaT,NaN,NaN,NaN,9234603292,USA

In [19]:
df.to_csv(
    "cleaned_date.csv",
    index=False
)